### ISSUE TITLE
[Documentation] About account pool?

### ISSUE THREAD

**Issue by OliverGrace** [fuergaosi233/wechat-chatgpt#147]
```
chatGPTAccountPool:
  - email: <your email>
    password: <your password>
chatPrivateTiggerKeyword: ""
  - session_token: <another account token>
```
Will these 2 accounts reload and renew automatically?

**Comment by RealTong** [comment]
Please note that there is an error in your configuration file

If you want to add multiple accounts it should be this
```yaml
chatGPTAccountPool:
  - email: <your email>
    password: <your password>
    session_token: <another account token>
  - email: <your email>
    password: <your password>
    session_token: <another account token>
chatPrivateTiggerKeyword: ""
```
