### ISSUE TITLE
能否触发回答登陆微信自己的发送问题？

### ISSUE THREAD

**Issue by hutao562** [fuergaosi233/wechat-chatgpt#235]
比如我就用自己的微信A登陆对接，能否触chatgpt回答发A发送的问题呢？

**Comment by sunshanpeng** [comment]
机器人自己的消息都过滤了，不然机器人会拿自己的消息作为输入。如果有需求你可以fork一份改下，去掉`chatgpt.ts`文件的`321`行`talker.self() ||`，再配上`chatPrivateTiggerKeyword`试试
```typescript
isNonsense(
    talker: ContactInterface,
    messageType: MessageType,
    text: string
  ): boolean {
    return (
      talker.self() || //去掉这行代码
      messageType > MessageType.GroupNote ||
      talker.name() == "微信团队" ||
      // 语音(视频)消息
      text.includes("收到一条视频/语音聊天消息，请在手机上查看") ||
      // 红包消息
      text.includes("收到红包，请在手机上查看") ||
      // 位置消息
      text.includes("/cgi-bin/mmwebwx-bin/webwxgetpubliclinkimg")
    );
  }
```

```yaml
chatGPTAccountPool:
  - email: email
    password: password
    session_token: session_token
chatPrivateTiggerKeyword: ""  # 加上这个配置
openAIProxy: ""
```
