### ISSUE TITLE
能不能加一个过滤词的功能呢,群里总有傻逼问政治问题我吐了

### ISSUE THREAD

**Issue by peterhiking** [fuergaosi233/wechat-chatgpt#246]

**Comment by peterhiking** [comment]
跟一个ai因为政治问题吵起来我也是吐了

**Comment by unixcs** [comment]
请问如何接入群呢？

**Comment by inannan423** [comment]
> 请问如何接入群呢？

拉进群就好了

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/tree/feat/add-block-word
我在这个分支添加了屏蔽词功能. (将屏蔽词配置在config.yaml就可以了)
```yaml
chatGPTAccountPool:
  - email: EMAIL
    password: PASSWORD
chatPrivateTiggerKeyword: "/chat "
blockWords: ["block1","block2","block3"]
```
