### ISSUE TITLE
🫰入群交流：账号密码登录报验证码错误，token 登录一直有问题：Error: ⚠️ No chatgpt item in pool 

### ISSUE THREAD

**Issue by smallersoup** [fuergaosi233/wechat-chatgpt#337]

**Comment by smallersoup** [comment]
最新的代码打包的镜像，token 登录一直有问题：
config.yaml 配置：
```yaml
chatGPTAccountPool:
  - session_token: "exmMSXujRpUMeggexqCIEg6O5V7w-nlxtgGaB6HFMXvrgnx"
clearanceToken: "j_xxx53cJsZxXExlD.0mE-1670845930-0-160"
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
openAIProxy: "127.0.0.1:7890"
```

```shell
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:200:13)
    at ChatGPTPoole.sendMessage (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:219:35)
    at ChatGPTPoole.sendMessage (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:230:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:286:12)
    at async ChatGPTBot.onGroupMessage (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:351:24)
    at async ChatGPTBot.onMessage (file:///Users/liliang22/github/wechat-chatgpt/src/chatgpt.ts:369:16)
    at async WechatyImpl.<anonymous> (file:///Users/liliang22/github/wechat-chatgpt/src/main.ts:32:9)
```
